#!/usr/bin/env bash
# This script is displaying specific phrases and numbers at different index
i=1
while [[ $i -lt 21 ]]; do
    case "$i" in
    "4")
      echo -e "4\nbad luck from China"
      ;;
    "9")
      echo -e "9\nbad luck from Japan"
      ;;
    "17")
      echo -e "17\nbad luck from Italy"
      ;;
    *)
    echo "$i"
  esac
  i="$((i + 1))"
done